#################################
# PID parameters for pose seeking
#################################

# Maximum value of error integral for all PID controllers
windup_limit: 0.05

# PID gains
joint_proportional_gain: 0.7
joint_integral_gain: 0.1
joint_derivative_gain: 0.5
joint_reach_tolerance: 0.03
